spring.application.name=bake-backend
# Server
server.port=8080

# H2 - lưu file thay vì RAM
spring.datasource.url=jdbc:h2:file:./data/bakedb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (xem database trên trình duyệt)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Load data mẫu khi khởi động
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

jwt.secret=bake_super_secret_key_2024_must_be_32_chars_min
jwt.expiration=86400000