-- H2 2.3.232;
;             
CREATE USER IF NOT EXISTS "SA" SALT '5f3044082a852da7' HASH '761bdf134795cdbfb13f5825aac7a2fb9658e596747e5a10e22ec4d192fafb9a' ADMIN;         
CREATE CACHED TABLE "PUBLIC"."CATEGORIES"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 6) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL
);           
ALTER TABLE "PUBLIC"."CATEGORIES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");   
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.CATEGORIES;              
INSERT INTO "PUBLIC"."CATEGORIES" VALUES
(1, 'Cake'),
(2, 'Cupcake'),
(3, 'Macaron'),
(4, 'Cookie'),
(5, 'Dessert');     
CREATE CACHED TABLE "PUBLIC"."ORDER_ITEMS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 100006) NOT NULL,
    "PRICE" FLOAT(53) NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    "ORDER_ID" BIGINT,
    "PRODUCT_ID" BIGINT
);             
ALTER TABLE "PUBLIC"."ORDER_ITEMS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");  
-- 16 +/- SELECT COUNT(*) FROM PUBLIC.ORDER_ITEMS;            
INSERT INTO "PUBLIC"."ORDER_ITEMS" VALUES
(1, 250000.0, 2, 1, 1),
(2, 35000.0, 1, 1, 3),
(3, 250000.0, 1, 4, 1),
(4, 280000.0, 2, 4, 2),
(5, 35000.0, 1, 4, 3),
(6, 250000.0, 1, 5, 1),
(7, 280000.0, 1, 6, 2),
(1000, 240000.0, 1, 1000, 1),
(1001, 35000.0, 2, 1000, 3),
(1002, 260000.0, 1, 1001, 9),
(100000, 270000.0, 1, 100000, 4),
(100001, 45000.0, 2, 100000, 25),
(100002, 270000.0, 1, 100001, 4),
(100003, 45000.0, 2, 100001, 25),
(100004, 220000.0, 1, 100002, 2),
(100005, 35000.0, 1, 100002, 7);           
CREATE CACHED TABLE "PUBLIC"."ORDERS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 100003) NOT NULL,
    "ADDRESS" CHARACTER VARYING(255) NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "STATUS" ENUM('CANCELLED', 'DONE', 'PENDING', 'PROCESSING', 'SHIPPING'),
    "TOTAL" FLOAT(53) NOT NULL,
    "USER_ID" BIGINT NOT NULL
);        
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");       
-- 9 +/- SELECT COUNT(*) FROM PUBLIC.ORDERS;  
INSERT INTO "PUBLIC"."ORDERS" VALUES
(1, U&'123 \00e1dasNguy\1ec5n Hu\1ec7, Q1, HCM', TIMESTAMP '2026-05-08 14:10:32.378154', 'PROCESSING', 535000.0, 1),
(4, U&'\00e1dads - 0123456789 - aaaaaaaa', TIMESTAMP '2026-05-08 14:49:31.350584', 'PENDING', 845000.0, 1),
(5, 'aaaaaaa - 0123456789 - d', TIMESTAMP '2026-05-08 15:02:33.337627', 'PENDING', 250000.0, 1),
(6, 'a - 0123456789 - a', TIMESTAMP '2026-05-08 15:06:59.023816', 'PENDING', 280000.0, 1),
(1000, 'Test User - 0900000000 - Test Address', TIMESTAMP '2026-06-02 20:44:10.028429', 'PENDING', 310000.0, 1),
(1001, 'a - a - a - Note: a', TIMESTAMP '2026-06-02 20:49:17.33534', 'PENDING', 260000.0, 1),
(100000, 'Test User - 0900000000 - Test Address', TIMESTAMP '2026-06-02 21:08:41.100435', 'PENDING', 360000.0, 1),
(100001, 'Test User - 0900000000 - Test Address', TIMESTAMP '2026-06-02 23:37:48.566962', 'PENDING', 360000.0, 1),
(100002, 'a - a - a - Note: a', TIMESTAMP '2026-06-03 00:05:42.379512', 'PENDING', 255000.0, 1);              
CREATE CACHED TABLE "PUBLIC"."PRODUCTS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 31) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING,
    "IMAGE" CHARACTER VARYING(255),
    "IS_ACTIVE" BOOLEAN,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "PRICE" FLOAT(53) NOT NULL,
    "CATEGORY_ID" BIGINT
);           
ALTER TABLE "PUBLIC"."PRODUCTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ID");     
-- 30 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCTS;               
INSERT INTO "PUBLIC"."PRODUCTS" VALUES
(1, 'Rich chocolate sponge with smooth chocolate ganache.', 'img/products/Chocolate Cake.jpg', TRUE, 'Chocolate Cake', 240000.0, 1),
(2, 'Soft vanilla cake with fresh strawberries and cream.', 'img/products/Strawberry Cake.jpg', TRUE, 'Strawberry Cake', 220000.0, 1),
(3, 'Classic red velvet with rich cream cheese frosting.', 'img/products/Red Velvet Cake.jpg', TRUE, 'Red Velvet Cake', 250000.0, 1),
(4, 'Chocolate cake layered with cherries and whipped cream.', 'img/products/Black Forest Cake.jpg', TRUE, 'Black Forest Cake', 270000.0, 1),
(5, 'Coffee-soaked cake with mascarpone cream and cocoa.', 'img/products/Tiramisu Cake.jpg', TRUE, 'Tiramisu Cake', 280000.0, 1),
(6, 'Special berry cake with light cream and fresh fruit.', 'img/products/Berry Celebration Cake.jpg', TRUE, 'Berry Celebration Cake', 260000.0, 1),
(7, 'Fluffy cupcake with blueberry cream cheese frosting.', 'img/products/Blueberry Cupcake.jpg', TRUE, 'Blueberry Cupcake', 35000.0, 2),
(8, 'Moist chocolate cupcake with creamy frosting.', 'img/products/Chocolate Cupcake.jpg', TRUE, 'Chocolate Cupcake', 32000.0, 2),
(9, 'Soft vanilla cupcake with silky buttercream.', 'img/products/Vanilla Cupcake.jpg', TRUE, 'Vanilla Cupcake', 30000.0, 2),
(10, 'Sweet strawberry cupcake with pink frosting.', 'img/products/Strawberry Cupcake.jpg', TRUE, 'Strawberry Cupcake', 33000.0, 2),
(11, 'Caramel cupcake finished with salted caramel cream.', 'img/products/Salted Caramel Cupcake.jpg', TRUE, 'Salted Caramel Cupcake', 36000.0, 2),
(12, 'Matcha cupcake with creamy green tea frosting.', 'img/products/Matcha Cupcake.jpg', TRUE, 'Matcha Cupcake', 34000.0, 2),
(13, 'Assorted French macarons with sweet filling.', 'img/products/Macaron Mix.jpg', TRUE, 'Macaron Mix', 120000.0, 3),
(14, 'Sweet raspberry macarons with soft cream.', 'img/products/Raspberry Macaron.jpg', TRUE, 'Raspberry Macaron', 120000.0, 3),
(15, 'Nutty pistachio macarons with delicate filling.', 'img/products/Pistachio Macaron.jpg', TRUE, 'Pistachio Macaron', 125000.0, 3),
(16, 'Chocolate macarons with rich ganache filling.', 'img/products/Chocolate Macaron.jpg', TRUE, 'Chocolate Macaron', 115000.0, 3),
(17, 'Classic vanilla macarons with smooth cream.', 'img/products/Vanilla Macaron.jpg', TRUE, 'Vanilla Macaron', 110000.0, 3),
(18, 'Bright lemon macarons with citrus filling.', 'img/products/Lemon Macaron.jpg', TRUE, 'Lemon Macaron', 115000.0, 3),
(19, 'Crisp cookies with chocolate chips inside.', 'img/products/Chocolate Cookie.jpg', TRUE, 'Chocolate Cookie', 22000.0, 4),
(20, 'Golden cookies packed with chocolate chips.', 'img/products/Chocolate Chip Cookie.jpg', TRUE, 'Chocolate Chip Cookie', 24000.0, 4),
(21, 'Chewy oatmeal cookie with sweet raisins.', 'img/products/Oatmeal Raisin Cookie.jpg', TRUE, 'Oatmeal Raisin Cookie', 23000.0, 4),
(22, 'Deep chocolate cookie with extra chocolate chunks.', 'img/products/Double Chocolate Cookie.jpg', TRUE, 'Double Chocolate Cookie', 26000.0, 4),
(23, 'Classic buttery cookie with a tender crumb.', 'img/products/Butter Cookie.jpg', TRUE, 'Butter Cookie', 20000.0, 4),
(24, 'Crunchy almond cookie with a toasted nut finish.', 'img/products/Almond Cookie.jpg', TRUE, 'Almond Cookie', 25000.0, 4),
(25, 'Tangy lemon filling with buttery tart crust.', 'img/products/Lemon Tart.jpg', TRUE, 'Lemon Tart', 45000.0, 5),
(26, 'Colorful fruit tart with custard and crisp crust.', 'img/products/Fruit Tart.jpg', TRUE, 'Fruit Tart', 52000.0, 5),
(27, 'Silky chocolate mousse with a rich cocoa taste.', 'img/products/Chocolate Mousse.jpg', TRUE, 'Chocolate Mousse', 48000.0, 5),
(28, 'Creamy panna cotta with a delicate vanilla finish.', 'img/products/Panna Cotta.jpg', TRUE, 'Panna Cotta', 46000.0, 5),
(29, 'Creamy cheesecake slice with a buttery base.', 'img/products/Cheesecake Slice.jpg', TRUE, 'Cheesecake Slice', 55000.0, 5),
(30, 'Custard dessert with caramelized sugar topping.', 'img/products/Creme Brulee.jpg', TRUE, 'Creme Brulee', 58000.0, 5);       
CREATE CACHED TABLE "PUBLIC"."USERS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) NOT NULL,
    "EMAIL" CHARACTER VARYING(255) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "PASSWORD" CHARACTER VARYING(255) NOT NULL,
    "ROLE" ENUM('ADMIN', 'USER')
);              
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");        
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
INSERT INTO "PUBLIC"."USERS" VALUES
(1, 'admin@bake.com', 'Admin', '$2a$10$xmO/1ZYwkf11uZmYh3ZuLObMiuX7lwoIhD1utU1Xh5NtGBloRTlY6', 'ADMIN'); 
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."UK6DOTKOTT2KJSP8VW4D0M25FB7" UNIQUE NULLS DISTINCT ("EMAIL");           
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."FK32QL8UBNTJ5UH44PH9659TIIH" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."ORDER_ITEMS" ADD CONSTRAINT "PUBLIC"."FKBIOXGBV59VETRXE0EJFUBEP1W" FOREIGN KEY("ORDER_ID") REFERENCES "PUBLIC"."ORDERS"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."PRODUCTS" ADD CONSTRAINT "PUBLIC"."FKOG2RP4QTHBTT2LFYHFO32LSW9" FOREIGN KEY("CATEGORY_ID") REFERENCES "PUBLIC"."CATEGORIES"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."ORDER_ITEMS" ADD CONSTRAINT "PUBLIC"."FKOCIMC7DTR037RH4LS4L95NLFI" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCTS"("ID") NOCHECK;              
